name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: custom-nginx/docker hub

    - name: Build and Push Docker Image
      run: |
        docker build -t custom-nginx .
        docker tag nginx deoatharva4/custom-nginx:latest
        docker push deoatharva4/custom-nginx:latest
    - name: Deploy to Server
      run: |
        ssh cloud_user@8a47b1701b3c.mylabserver.com "docker pull deoatharva4/custom-nginx:latest"
        ssh cloud_user@8a47b1701b3c.mylabserver.com "docker run -d -p 1234:80 deoatharva4/custom-nginx:latest"
