name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
 
    - name: Build and Push Docker Image
      run: |
        docker build -t custom-nginx .
        docker tag custom-nginx deoatharva4/custom-nginx:latest
        docker push deoatharva4/custom-nginx:latest
        
  ##  - name: Set up SSH
   ##   uses: webfactory/ssh-agent@v0
     ## with:
       ## ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    ##- name: Deploy to server
      ##run: |

    - name: Deploy to Server
      run: |
        ssh cloud_user@your-server-ip "docker pull deoatharva4/custom-nginx:latest"
        ssh cloud_user@your-server-ip "docker stop custom-nginx || true"
        ssh cloud_user@your-server-ip "docker rm custom-nginx || true"
        ssh cloud_user@your-server-ip "docker run -d -p 1234:80 --name custom-nginx deoatharva4/custom-nginx:latest"      
        
